### ISSUE TITLE
assert with a function call

### ISSUE THREAD

**Issue by jeparlefrancais** [Kampfkarren/selene#103]
Selene gives a lint when using assert without 2 parameters, but it does not consider that a function call can return multiple values.

It's usually ok but when using [`t`](https://github.com/Roblox/t) it does not like this:
```lua
assert(t.number(foo))
```

The message:
```
standard library function `assert` requires 2 parameters, 1 passed
```

Also, technically `assert` can accept one argument, but I like the idea that selene could suggest (with maybe just a warning) that `assert` is missing the second argument.

**Comment by Kampfkarren** [comment]
Someone reported this on the OSS discord (maybe you?), but this is a bug with the standard library lint, yeah.
