### ISSUE TITLE
Camera.CFrame does not contain :ToEulerAngles

### ISSUE THREAD

**Issue by LouieK22** [Kampfkarren/selene#104]
`workspace.CurrentCamera.CFrame:ToEulerAnglesYXZ()` causes the error

> standard library global \`workspace.CurrentCamera.CFrame\` does not contain the field \`ToEulerAnglesYXZ\`

**Comment by Kampfkarren** [comment]
Possible duplicate of #74

**Comment by LouieK22** [comment]
Seems like the same root cause. Closing in favor of #74
