### ISSUE TITLE
Turn off allow_unused_self lint by default?

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/selene#112]
This is an easy change, but just a matter of if its a good idea--it seems to be the only thing anyone changes in the config files from a check of selene.tomls on GitHub.

**Comment by dekkonot** [comment]
There's plenty of reasons to use the colon syntax for defining methods even if said method is static -- at the very least, it helps maintain consistency.

I'm in favor of disabling it by default just to save people trouble.
