### ISSUE TITLE
standard library function `Instance.new` requires 1 parameters, 2 passed

### ISSUE THREAD

**Issue by ReinitiaIized** [Kampfkarren/selene#114]
**What's happening:**
selene is throwing a complaint regarding the second parameter of Instance.new not being valid
![unknown 1](https://user-images.githubusercontent.com/20674500/83531702-f2088500-a4b2-11ea-9e31-87ef7443f727.png)

**What should happen**
selene should not be complaining as it is a valid parameter

**Comment by Kampfkarren** [comment]
This is intentional. You should not be using the second parameter of Instance.new as it is not idiomatic at best, ill performant at worst.

**Comment by ReinitiaIized** [comment]
I actually remembered the use case for this. 

Say I have a need to use a BindableEvent for suspending the calling thread, however I don't need to change any of its properties beyond parenting it, then destroying it after its been used. This is a case where I argue a **strong** warning should be pushed, stating performance reasons, but not outright calling it an error.

**Comment by Kampfkarren** [comment]
You should still set the parent property instead for consistency.
