### ISSUE TITLE
Instance.new with 2 variables

### ISSUE THREAD

**Issue by shadownetdev1** [Kampfkarren/selene#115]
Selene tells me that Instance.new() expects 1 variable when it actually expects 1 or 2 variables.
![image](https://user-images.githubusercontent.com/26750646/83686561-64af5880-a5b8-11ea-917d-7ec60dbd6ca4.png)
The valid variables are "string val" and "Instance parent".
![image](https://user-images.githubusercontent.com/26750646/83686846-f028e980-a5b8-11ea-8dda-22033922f323.png)

I use the "Instance parent" variable often because it requires less typing and runs a little faster in execution. It would be appreciated if this could be fix at some point.
Thank you

**Comment by Kampfkarren** [comment]
Intentional behavior: https://github.com/Kampfkarren/selene/issues/114#issuecomment-637844358
