### ISSUE TITLE
Selene marks "continue" keyword as an error 

### ISSUE THREAD

**Issue by Klicer** [Kampfkarren/selene#118]
![image](https://user-images.githubusercontent.com/51763508/84580199-79bc9080-addd-11ea-9adc-a94b80387ed2.png)
Roblox has actually supported the continue keyword for a while. 
![image](https://user-images.githubusercontent.com/51763508/84580214-9b1d7c80-addd-11ea-8f19-00916fc6de20.png)
Please add this to the roblox selene thing.

**Comment by Kampfkarren** [comment]
https://github.com/Kampfkarren/full-moon/issues/59
