### ISSUE TITLE
require(mainModuleId) is flagged as incorrect

### ISSUE THREAD

**Issue by 1ForeverHD** [Kampfkarren/selene#123]
![image](https://user-images.githubusercontent.com/51117782/86009529-3d5e7680-ba12-11ea-991a-83dedd6d1a5a.png)

**Comment by Kampfkarren** [comment]
This was an oversight, but I'm hesitant to allow this since in general this is a bad idea, to allow your dependencies to just update without you doing it manually.

**Comment by 1ForeverHD** [comment]
I agree this isn't best practise, however HttpService for one of my projects cannot be depended upon for all users, therefore requiring MainModules is the next best alternative. Is it possible to introduce a setting to disable/enable this warning, remaining enabled by default?

**Comment by Kampfkarren** [comment]
HttpService wouldn't be correct either, I don't think you should be requiring anythign externally at all. Why can't you just have it in with the rest of your code?

**Comment by Kampfkarren** [comment]
I don't think you should be using require by ID. In the future this can have a more clear error message.
