### ISSUE TITLE
vararg and `arg` table are not defined in Lua 5.1 standard lib

### ISSUE THREAD

**Issue by Dekkonot** [Kampfkarren/selene#124]
When command line arguments are passed to vanilla Lua, they show up as a vararg (...) or a global table named `arg`. Seems reasonable to define them in the 5.1 standard lib.

**Comment by Kampfkarren** [comment]
Just having `...` in the standard library file would probably make this work:

```lua
local foo = { ... } -- good!

local function foo()
    return ... -- oh no, selene says this is good, but it shouldn't be
end
```

It's a good stopgap solution, but a bad long term solution.
