### ISSUE TITLE
How to define global variables for TestEZ

### ISSUE THREAD

**Issue by Eyytrix** [Kampfkarren/selene#126]
Hello, I have been using TestEZ to test my codes. 

The issue is the functions `describe`, `it`, and `expect` are injected by TestEZ, so Selene marks them as undefined variables. 
![Screen Shot 2020-07-03 at 5 38 45 PM](https://user-images.githubusercontent.com/24510019/86502096-4c1b9500-bd54-11ea-9a38-3fbcb8a607e9.png)

I followed the doc and tried to make a new standard library to declare them as global functions, but failed to so. Any suggestions?

**Comment by Kampfkarren** [comment]
You can find an example here: https://github.com/Kampfkarren/Roblox/

**Comment by Eyytrix** [comment]
Thank you so much.
