### ISSUE TITLE
Add column ending to -q mode.

### ISSUE THREAD

**Issue by howmanysmall** [Kampfkarren/selene#129]
The only mode that seems to include this is `--display-mode=json`, which is significantly harder to match and doesn't include the line of the problem. Neither of these options are suitable for the SublimeLinter implementation of selene I'm trying to create, which is disappointing.

```json
{
	"severity":"Warning",
	"code":"unused_variable",
	"message":"HelloWorld is defined, but never used",
	"primary_label": {
		"file_id":0,
		"span": {"start":9,"end":19}, // No line?
		"message":""
	},
	"notes":[],
	"secondary_labels":[]
}
```

This includes the line of the error, and the general position (?) of the error, but not the full span.
`luatestcode.lua:1:10: warning[unused_variable]: HelloWorld is defined, but never used`

**Comment by Kampfkarren** [comment]
It feels like the better solution is to make the JSON output better, no? I would rather any external tooling use that rather than try to parse the text format we have, which is not documented and is subject to change.

**Comment by howmanysmall** [comment]
Yeah, I was thinking the same thing, since I decided to suck it up and parse the json, provided it won't change in the future, it'll work.

**Comment by Kampfkarren** [comment]
Can you please file an issue for whatever problems JSON has?
