### ISSUE TITLE
Selene doesn't respect local variables

### ISSUE THREAD

**Issue by Kenji-Shore** [Kampfkarren/selene#135]
https://i.imgur.com/ikud6BI.png

Redefining a variable locally in different scopes is a valid use case of Lua, but Selene complains that the local variable has been previously defined.

**Comment by Kampfkarren** [comment]
Not a bug. Selene isn't saying the code isn't correct, it's saying you're shadowing.

https://kampfkarren.github.io/selene/lints/shadowing.html
