### ISSUE TITLE
Ignore 1-line 'continue' statements

### ISSUE THREAD

**Issue by OttoHatt** [Kampfkarren/selene#138]
Both ```return``` and ```break``` can be used in one-line statements, but ```continue``` can't, which doesn't seem consistent. 

```lua
-- OK
if (not A) then return end

-- OK
if (not A) then break end

-- Error - "only one statement per line is allowed selene::multiple_statements"
if (not A) then continue end
```

**Comment by Kampfkarren** [comment]
Fixed by https://github.com/Kampfkarren/full-moon/issues/79.

**Comment by Kampfkarren** [comment]
Should be fixed in latest selenes.

**Comment by Kampfkarren** [comment]
"Warn type: 1" is not any language selene would use, neither is "expression cannot be used as a statement".

Your bug seems to be coming from "luahelper-lsp".

https://sourcegraph.com/github.com/Tencent/LuaHelper/-/blob/luahelper-lsp/langserver/check/compiler/parser/parse_stat.go?L481
