### ISSUE TITLE
Labels are incorrectly flagged as invalid syntax

### ISSUE THREAD

**Issue by jshtab** [Kampfkarren/selene#145]
Labels (defined [here](https://www.lua.org/manual/5.3/manual.html#3.3.4), since 5.2) are linted as syntax errors.

![image](https://user-images.githubusercontent.com/60208437/88795727-7fdcb580-d16e-11ea-9811-99e6f167954c.png)

**Comment by Kampfkarren** [comment]
Full Moon, and by extension Selene, only support Lua 5.1.
