### ISSUE TITLE
Selene does not support UICorner

### ISSUE THREAD

**Issue by LouieK22** [Kampfkarren/selene#147]
```lua
Roact.createElement("UICorner", {
	CornerRadius = UDim.new(0, 6),
})
```

will fail since `` `UICorner` is not a valid class``

**Comment by Jaguar-515** [comment]
This is due to the [rbx_reflection crate](https://github.com/Roblox/rbx-dom/tree/master/rbx_reflection) not updated as of now to support UICorner in rbx_reflection's database.

**Comment by Kampfkarren** [comment]
I'm going to close this in favor of #91, since they're functionally the same.
