### ISSUE TITLE
Foreman installs the selene-light executable instead of selene on Linux

### ISSUE THREAD

**Issue by kennethloeffler** [Kampfkarren/selene#151]
To reproduce, use [foreman](https://github.com/Roblox/foreman) to install the latest version of selene on Linux; attempting to use Roblox features such as `generate-roblox-std` will fail. Foreman selects the executable at the first index of a release archive when installing, so this might be happening because `selene-light` was zipped into `selene-0.8.0-linux.zip` before `selene`.

**Comment by Kampfkarren** [comment]
This would be an issue with how I do it all manually, stuff like this happens.

I need to spend just a bit of time automating it.
