### ISSUE TITLE
Defining a global and attempting to use it in a function body gives an unused variable warning

### ISSUE THREAD

**Issue by ok-nick** [Kampfkarren/selene#157]
![image](https://user-images.githubusercontent.com/25470747/93954856-7b6eec00-fd1c-11ea-9bd6-2f955c23ea35.png)
![image](https://user-images.githubusercontent.com/25470747/93954862-7f027300-fd1c-11ea-83e6-0bc88d87142b.png)
![image](https://user-images.githubusercontent.com/25470747/93954870-8295fa00-fd1c-11ea-8930-9a834ee23fe2.png)
![image](https://user-images.githubusercontent.com/25470747/93954884-87f34480-fd1c-11ea-8871-d1fb23e52620.png)

**Comment by Kampfkarren** [comment]
The original title you gave was not accurate--Roblox standard libraries don't give unused warnings, for example. I've updated it appropriately.

**Comment by Kampfkarren** [comment]
There's two bugs here.

One is that you can't properly override things with `any: true`.

The other is that `unused_variable` steps in and says its defined, but not used, which is incorrect. This code errors, and selene should be able to catch that.
