### ISSUE TITLE
Errors on offline startup with the vscode extension

### ISSUE THREAD

**Issue by ghost** [Kampfkarren/selene#174]
Getting 2 errors when trying to start the selene vscode extension when offline:

![image](https://user-images.githubusercontent.com/65620355/98414811-58a25800-207c-11eb-9362-07fb92781da7.png)

**Comment by Kampfkarren** [comment]
Does the rest of the extension continue to work?

**Comment by Kampfkarren** [comment]
Duplicate of #73
