### ISSUE TITLE
Roblox error can accept any type for first argument

### ISSUE THREAD

**Issue by matthargett** [Kampfkarren/selene#180]
Using selene 0.9.2, I'm seeing this output:
```
error[incorrect_standard_library_use]: use of standard_library function `error` is incorrect
    ┌─ StackFrame.lua:113:10
    │
113 │               error({
    │ ╭───────────────────^
114 │ │                 stack = debug.traceback(),
115 │ │             })
    │ ╰─────────────^ expected `string`, received `table`
```

The (correct) error definition for Lua 5.1 is here, https://github.com/Kampfkarren/selene/blob/master/selene-lib/default_std/lua51.toml#L32
but Roblox Lua allows for a table to be given for the first argument as well. 

It looks like the place to insert this might be here: https://github.com/Kampfkarren/selene/blob/master/selene/src/roblox.rs#L49
but I'm not sure. If someone can point me to where the right place for the enhancement is, I'll submit a PR.

**Comment by Dekkonot** [comment]
Does `error` actually allow that? I wasn't aware. Is that documented anywhere?

**Comment by Kampfkarren** [comment]
The place to put it is here--https://github.com/Kampfkarren/selene/blob/master/selene/src/roblox/base.toml
