### ISSUE TITLE
ProximityPromptService missing from Services

### ISSUE THREAD

**Issue by Dev0mar** [Kampfkarren/selene#188]
When attempting to get [ProximityPromptService](https://developer.roblox.com/en-us/articles/proximity-prompts) using `game:GetService()` it gives me a red underline saying its incorrect usage.

![image](https://user-images.githubusercontent.com/3249781/102263611-37efdc80-3f1d-11eb-830a-ccc96119988d.png)

**Comment by Kampfkarren** [comment]
Delete `roblox.toml`.
