### ISSUE TITLE
Short-hand array type check raises error

### ISSUE THREAD

**Issue by benbrimeyer** [Kampfkarren/selene#197]
[Spec](https://roblox.github.io/luau/typecheck.html) (scroll down to Table indexers)
0.10.0 doesnt seem to support array-like table shorthand yet:

Selene will complain:
```lua
local spreadPattern: { Vector2 } = { Vector2.new() }
```

but long form is fine:
```lua
local spreadPattern: { [number]: Vector2 } = { Vector2.new() }
```

**Comment by Kampfkarren** [comment]
This should be fixed by now, but I'm going to keep the issue up until we get a unit test for it.

**Comment by Kampfkarren** [comment]
Probably don't need to actually, considering full-moon should have plenty
