### ISSUE TITLE
roblox.toml is being re-generated even if it already exists

### ISSUE THREAD

**Issue by oltrep** [Kampfkarren/selene#201]
In a project, I have `roblox.toml` file that may contain certain modifications, but when I run selene on the project, it still prints this message and overwrites the file:

```
`std = "roblox"`, but there is no roblox.toml in this directory. We are automatically generating one for you now!
```

**Comment by Kampfkarren** [comment]
I'm not sure you should be modifying roblox.toml at all. This doesn't seem like something I want to support.

Let me know if this still happens with no modifications.

**Comment by oltrep** [comment]
I don't think it happens with no modifications.

I do think it's still worth to support though. I thought the point of having a configuration file like this was to allow the user to modify it as like with any other configuration file. It is useful when new features are not necessary out yet, but you can still add them to the file 🙂 

Also, users don't have to re-install selene just to fix something related to roblox globals. For example, the recent changes to `math.round`, `UDim.new`, `UDim2.fromOffset`, etc: those are all fixable just by change the config file, so users don't need to wait for a whole new selene release before having the fix.

If you don't want to support it, I would suggest just removing the whole roblox config file generation, and just keep it in memory. Writing it to the file system and overriding changes anyway just to read it back seems like unnecessary work 🤷

**Comment by Kampfkarren** [comment]
If you want to have multiple `std` files, you can combine them like:

```toml
std = "roblox+something"
```

...and create a something.toml.

> If you don't want to support it, I would suggest just removing the whole roblox config file generation, and just keep it in memory. Writing it to the file system and overriding changes anyway just to read it back seems like unnecessary work 🤷

#125 aims to do that, I just haven't gotten around to it yet.

**Comment by oltrep** [comment]
Ok! So for `std = "roblox+something"`, having multiple definitions of the same function would resolve to the latest one? That's doable 🙂 And yeah #125 sounds great!

As a user though, I would still expect to be able to override the file, no matter if the tool is able to get a more recent one. It should do it when I want, and not override my local version. I could trigger the update with the `generate-roblox-std` command (or a future `fetch-latest-roblox-std`)
