### ISSUE TITLE
Parser errors but selene exit with code 0

### ISSUE THREAD

**Issue by jeparlefrancais** [Kampfkarren/selene#203]
I ran `selene src`, and it threw this error:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` 
value: ParseIntError { kind: InvalidDigit }', C:\...\.cargo\registry\src\
github.com-1ecc6299db9ec823\selene-lib-0.10.1\src\rules\
bad_string_escape.rs:129:88
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace     
Results:
0 errors
0 warnings
0 parse errors
```

But the exit code was still zero.

## Repro

Create a file with this:
```lua
return '\97b'
```

Run selene on the file and then you can run `echo $?` to print the last exit code.

**Comment by Kampfkarren** [comment]
This is two separate requests--a feature request for panics to have a non-zero exit code (I agree), and a bug report for `'\97b'` panicking (nothing should ever panic!), can you file a separate issue for the latter?
