### ISSUE TITLE
@ and $ cancels linting in a file and isn't expressed through the extension

### ISSUE THREAD

**Issue by ok-nick** [Kampfkarren/selene#207]
![G75zzVo4T2](https://user-images.githubusercontent.com/25470747/106815821-6eef8e00-6642-11eb-8b0e-dbf485683e88.gif)

**Comment by Kampfkarren** [comment]
Parsing errors cancelling all linting isn't a bug, but selene not telling you the problem is the @/$ sign is.

**Comment by Kampfkarren** [comment]
Duplicate of #76
