### ISSUE TITLE
Integration into an LSP

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/selene#22]
Major feature luacheck has over selene--there's like a thousand extensions that support it for just Visual Studio Code alone.

**Comment by Kampfkarren** [comment]
Selene now has a [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=Kampfkarren.selene-vscode&ssr=false#qna)!

**Comment by Stanzilla** [comment]
Should probably list that in the README :D

**Comment by Kampfkarren** [comment]
I still need to put this in the README (and the documentation), but this issue itself can be closed.

**Comment by antonk52** [comment]
Would it be possible to still provide an lsp cli to be able to integrate with other text editors that support language servers? Most code can be reused with the current vscode plugin implementation.

A few examples of text editors that support LSP: neovim, emacs, zed, helix
