### ISSUE TITLE
Feature request: add support for sealed tables

### ISSUE THREAD

**Issue by cassis163** [Kampfkarren/selene#234]
This linter does not throw an error when a sealed table (Luau) is used incorrectly. For example, this code
```lua
local sealedTable = { x = 1 }
sealedTable.y = 2
```
is allowed by selene, in contrast to the ROBLOX Luau linter.

**Comment by Kampfkarren** [comment]
"Sealed tables" aren't a real thing in Lua, it'd be inappropriate for selene to care about this since it's not really a sign of buggy or invalid code.

This is something best left for a linter that relies on types, which I consider out of scope for selene.
