### ISSUE TITLE
incorrect reading of negative ternary as bool

### ISSUE THREAD

**Issue by matthargett** [Kampfkarren/selene#238]
As discussed on Discord:
```
error[incorrect_standard_library_use]: use of standard_library function `UDim2.new` is incorrect
    ┌─ src\Add\Control\Bonk\BaseBonk.lua:120:40
    │
120 │                     Position = UDim2.new(0.1, 0, 0.9, not isLilyPadSelected and 2 or 0),
    │                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `number`, received `bool````

**Comment by Kampfkarren** [comment]
For posterity, it's because selene doesn't really have knowledge of precedence--so it sees this as `not (isLilyPadSelected and 2 or 0)`.

I wonder if this is fixed by the new full-moon version, but I don't think so--I think that only added precedence to binary operations.

**Comment by JohnnyMorganz** [comment]
Full-moon will now parse it as:
```
lhs:
   lhs: not isLilyPadSelected
   op: and
   rhs: 2
op: or
rhs: 0
```
Which should be the correct precedence for both binop and unop - but I don't know how selene handles evaluating it

**Comment by Kampfkarren** [comment]
It'll probably be good, I'll write a test after the update is done.

**Comment by Kampfkarren** [comment]
Fixed in the unpushed update.
