### ISSUE TITLE
Update installation instructions to work with main branch

### ISSUE THREAD

**Issue by tonycuadra** [Kampfkarren/selene#241]
When attempting to follow the installation instructions here:
https://kampfkarren.github.io/selene/cli/installation.html

I ran into an error with this command:
```cargo install --git https://github.com/Kampfkarren/selene selene```

It looks like `cargo install` still defaults to using the `master` branch and errors out if it does not exist. To workaround this, the correct branch name must be specified:

```cargo install --branch main --git https://github.com/Kampfkarren/selene selene```

**Comment by Kampfkarren** [comment]
Apparently this is on nightly, which should fix the problem, but for now, yeah this needs to be fixed.

https://github.com/rust-lang/cargo/pull/9133
