### ISSUE TITLE
Selene 0.12.1 is unable to parse type definitions like it was previously able to.

### ISSUE THREAD

**Issue by howmanysmall** [Kampfkarren/selene#254]
![image](https://user-images.githubusercontent.com/26746527/120113677-c7d6bb00-c138-11eb-93a9-1146bb4d6274.png)

The code that seems to break is whenever you do an interface definition with a function included, in my case it's:
```
type IProperties = {
	Position: Vector3,

	Bloom: Vector2?,
	Color: Color3?,
	Function: ((IProperties, number, number) -> nil)?,
	Global: boolean?,
	Gravity: Vector3?,
	Lifetime: number?,
	Occlusion: boolean?,
	RemoveOnCollision: (string | (IProperties, BasePart, Vector3, Vector3, Enum.Material, number) -> boolean)?,
	Size: Vector2?,
	Transparency: number?,
	Velocity: Vector3?,
	WindResistance: number?,
}
```

I'm not sure how to describe it, but removing the `Function: ((IProperties, number, number) -> nil)?,` and the `RemoveOnCollision: (string | (IProperties, BasePart, Vector3, Vector3, Enum.Material, number) -> boolean)?,` seems to fix it.

**Comment by Kampfkarren** [comment]
I believe this is fixed with a full-moon PR. I will get to it today if I remember.

**Comment by matthargett** [comment]
This is still a problem in the full-moon upgrade PR branch.

**Comment by Kampfkarren** [comment]
CC @JohnnyMorganz, any thoughts on this?

**Comment by JohnnyMorganz** [comment]
Ah yes, this does seem to be a full-moon issue.
The issue spans from the `Enum.Material` inside the function arguments. This hasn't been handled correctly.

**Comment by Kampfkarren** [comment]
Should be fixed with latest full moon update.
