### ISSUE TITLE
Set a global config for selene across workspaces

### ISSUE THREAD

**Issue by sasial-dev** [Kampfkarren/selene#268]
Set a global config for the extension which appiles to all workspaces.

**Comment by Kampfkarren** [comment]
First off, please make your issue title and description more descriptive.

Second, I could've sworn we already had an issue for this, but apparently not.

I'm hesitant on this because I think it makes knowing what selene configuration a repository is using more difficult.

**Comment by sasial-dev** [comment]
My use-case was that I've got https://roblox-ts.com/ and I've got selene screaming "game" isn't defined etc, and would like to have a default config across workspaces for `std = "roblox"`.

Maybe it would be better if you could just exclude files from selene in workspace .vscode/settings.json?

**Comment by Kampfkarren** [comment]
I don't see the benefit in supporting selene for roblox-ts codebases when you shouldn't care about its output. Why not just disable selene in those workspaces?

**Comment by sasial-dev** [comment]
Good point.
