### ISSUE TITLE
What's the equivalent of `--luacheck: globals vim` in Selene?

### ISSUE THREAD

**Issue by mystilleef** [Kampfkarren/selene#284]
`vim is not defined`

With `luacheck` you add the following to the top of the file and move on with life.

`--luacheck: globals vim`

Without creating a standard library or external configuration files, how do you do the same with `selene`?

I don't want to disable the `undefined_variable` check. I just want to whitelist `vim`.  

I'm using `selene` via an `lsp` and they're a pain to configure. So I appreciate linters that work out of the box without requiring external configuration.

**Comment by Kampfkarren** [comment]
[Standard libraries](https://kampfkarren.github.io/selene/usage/std.html).

You update your `selene.toml` file to include `std = "filename"`, then in `filename.toml` you would write out the details of `vim`.

If you want to take the easy route, filename.toml (of course, you can name this whatever you want), can literally just be:

```toml
[selene]
base = "lua51"

[vim]
any = true
```

...but you'd benefit from writing out the types properly, such as in [the example Lua 5.1 library](https://github.com/Kampfkarren/selene/blob/main/selene-lib/default_std/lua51.toml).

I found an example here:

**Comment by mystilleef** [comment]
Thank you. That looks easy enough. However, I was hoping not to have to maintain another config file. Can those options in the custom libraries and files be inlined into a comment that `selene` can understand? This is purely for “throw-away” use-cases where, ahem, lazy developers, strapped for time and patience, don't want to write a full-blown library. Great work, by the way.

**Comment by mystilleef** [comment]
Right under my nose, the `lsp` client I use for `selene` has a good library for `vim`. 

https://github.com/jose-elias-alvarez/null-ls.nvim

So, if you're lazy, like me, new users can look into `vim.toml`, `selene.toml` and `stylua.toml`

**Comment by unphased** [comment]
@mystilleef Can you please elaborate? I have `selene` installed via mason.nvim and the lints is served through null-ls, but where is selene.toml supposed to go?

**Comment by wangyandongnx** [comment]
> Right under my nose, the `lsp` client I use for `selene` has a good library for `vim`.
> 
> https://github.com/jose-elias-alvarez/null-ls.nvim
> 
> So, if you're lazy, like me, new users can look into `vim.toml`, `selene.toml` and `stylua.toml`

Thanks. This saved my day.
