### ISSUE TITLE
Add something like .gitignore which will make Selene not check specified directories

### ISSUE THREAD

**Issue by Aerodymier** [Kampfkarren/selene#289]
In Lua, sometimes libraries have a lot of warnings or/and errors and when I click on one of them, my "Problems" tab clutters with them. If this was available in Selene, I'd add libraries directory to that list and prevent this.

Also an excluding feature would be nice, for example if I want to not check the entire lib directory but check one file in it, it shall be possible.

**Comment by Kampfkarren** [comment]
Solved by #15
