### ISSUE TITLE
Error when setting `--config`

### ISSUE THREAD

**Issue by dstanberry** [Kampfkarren/selene#296]
selene fails whenever `--config` is passed with the following message:

`ERROR: Could not retrieve standard library: io error: No such file or directory (os error 2)`

I've checked that there are no file/path restrictions for the user the command runs as. Works as expected when ran from the directory the config file exists.

**Comment by Kampfkarren** [comment]
The bug is that it complains about standard libraries, and not about the missing config, right?

**Comment by dstanberry** [comment]
Right, but if the cwd is the same as the toml there is no error message, the lint is performed.

**Comment by henriquehbr** [comment]
I'm facing the same problem using `selene-light` on a `debian:bullseye-slim` docker image

**Comment by Kampfkarren** [comment]
I think this is the same as #339, so I'm closing this since that one has more information
