### ISSUE TITLE
Fix `selene::unused_variable` when using module for Luau types

### ISSUE THREAD

**Issue by vocksel** [Kampfkarren/selene#305]
I export types from a `types.lua` ModuleScript, and when I import the module and use my types Selene marks the `types` variable as being unused

![image](https://user-images.githubusercontent.com/3081936/136669158-e48d2f50-d449-422c-beed-f5058df33d50.png)

**Comment by Kampfkarren** [comment]
Oh, this is a duplicate of #270, I misread the title.
