### ISSUE TITLE
What's the difference between selene and selene-light

### ISSUE THREAD

**Issue by henriquehbr** [Kampfkarren/selene#306]
I've noticed that the latest release offers 2 different download options, and this got me thinking, if the light variant has less features or some limitations that aren't present on it's counterpart, because i'm really interested on using it

I tried searching around the release history, commit log, documentation, and even for the "light" keyword across the entire repo, and couldn't manage to find anything on the matter, wouldn't it be interesting to document this altenative version of selene?

**Comment by Kampfkarren** [comment]
It probably should be documented, yeah.

As of now, selene-light is identical to selene except it doesn't come with the Roblox features. In the future, the amount of alternative Cargo features selene might have could change, for example to support more Lua versions.
