### ISSUE TITLE
Unresolved imports and use of unstable library features

### ISSUE THREAD

**Issue by Sparkypen7** [Kampfkarren/selene#31]
When trying to install Selene via `cargo install selene`, several errors occur regarding to Unresolved imports and use of unstable library features.

![image](https://user-images.githubusercontent.com/11379504/68356504-7db66080-00e0-11ea-85ed-c44f1756a31c.png)

[log.txt](https://github.com/Kampfkarren/selene/files/3817681/log.txt)

These errors occurred when trying to install the most stable build of Selene.

**Comment by Kampfkarren** [comment]
Your Rust is out of date--TryFrom and TryInto have been stable since 1.34.0.

**Comment by Sparkypen7** [comment]
Thank you
