### ISSUE TITLE
Not working properly on Alpine container with gcompat

### ISSUE THREAD

**Issue by henriquehbr** [Kampfkarren/selene#311]
I'm running a docker container using the binary of selene-light 0.14.0, and by default, it doesn't work on Alpine (due to incompatibility with musl i suppose), so i'm using gcompat in order to patch this (as suggested by the [wiki](https://wiki.alpinelinux.org/wiki/Running_glibc_programs)), but looks like selene is not accepting args now, when i try to run it, i receive the following error message:

```
$ selene lua/project
error: The following required arguments were not provided:
    <files>...

USAGE:
    selene <files>... --color <color> --display-style <display-style> --num-threads <num-threads> --pattern <pattern>

For more information try --help
```

**Comment by Kampfkarren** [comment]
I'm going to assume this is fixed, the Docker URL (boyned/selene) has had a release published to it.
