### ISSUE TITLE
A per-project configuration file to stop linting for some kinds of warnings

### ISSUE THREAD

**Issue by Aerodymier** [Kampfkarren/selene#329]
This would be useful, for example I sometimes like to use multiple statements per one line when they are too short but I have to add the ignore comment to the line before that. 

I know that these are here to warn for bad practises but some things might not be considered as bad practise for some people like my example. I think having an optional per-project configuration file is a good way to solve this problem.

Additionally, there should be a way of also setting some script-specific rules in this configuration file. For example I would disable the proper rule in Remodel scripts so it won't lint all "remodel" keywords as undefined variable.
I know that there is a way of doing this currently but having a configuration file alongside other things it can do would look way more organized.

**Comment by Kampfkarren** [comment]
It's selene.toml.

https://kampfkarren.github.io/selene/usage/configuration.html
