### ISSUE TITLE
standard library function assert does *not* require 2 parameters

### ISSUE THREAD

**Issue by Aerosphia** [Kampfkarren/selene#332]
`assert` does **not** require 2 parameters, unlike what is proposed in the `incorrect_standard_library_use` lint.
When failing to provide a 2nd parameter, error messages are defaulted to `Assertion failed`

![image](https://user-images.githubusercontent.com/78659866/145698639-08ef9352-b2aa-44fb-8f0b-2c812bd64c2c.png)

https://streamable.com/np3tfk

**Comment by Kampfkarren** [comment]
Intentional, though it's a (reported?) bug that it doesn't tell you why.

https://github.com/Kampfkarren/selene/blob/main/selene-lib/default_std/lua51.toml#L16-L18
