### ISSUE TITLE
"plugin" is undefined

### ISSUE THREAD

**Issue by Aerosphia** [Kampfkarren/selene#333]
plugin is a keyword
you can see examples of it used [here](https://developer.roblox.com/en-us/articles/Intro-to-Plugins)

![image](https://user-images.githubusercontent.com/78659866/146512937-49c3f896-9730-4038-9250-f58c2310e74e.png)

**Comment by Kampfkarren** [comment]
roblox.toml defines `plugin`.  Make sure you set `std = "roblox"`.

![image](https://user-images.githubusercontent.com/3190756/146514384-28659904-80a1-4acc-9b09-343fb41cd1f1.png)

![image](https://user-images.githubusercontent.com/3190756/146514404-0e0ca949-91a6-4f39-955c-ebf02d1f8e38.png)
