### ISSUE TITLE
unable to use standard libraries unless I'm in the same working dir

### ISSUE THREAD

**Issue by ayushnix** [Kampfkarren/selene#339]
I've tried using several combinations but I can't figure out how to actually use this linter using a config file and inside neovim using [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim/) plugin.

**Attempt 1**: Using `selene --config ~/.config/selene/selene.toml ~/.config/nvim/lua`

The `selene.toml` file contains

```toml
std = "lua51+vim"
```

and another file, `vim.toml` in the same directory contains

```toml
[vim]
any = true
```

When I execute the command mentioned above, I get this output

```
`std = "lua51+vim"`, but some files could not be found:
  `lua51.toml`
  `vim.toml`
ERROR: Could not find all standard library files
```

**Attempt 2**: Using `selene --config ~/.config/selene/selene.toml .config/nvim/lua/`

The `selene.toml` file has the same contents mentioned [here](https://github.com/Kampfkarren/selene/issues/284#issuecomment-892970222)

```toml
# std = "lua51+vim"
[selene]
base = "lua51"

[vim]
any = true
```

This time, selene doesn't recognize the `vim` variable and throws lots of errors like

```
error[undefined_variable]: `vim` is not defined
  ┌─ .config/nvim/lua/autocmd.lua:4:13
  │
4 │ local cmd = vim.cmd
  │             ^^^
```

**Attempt 3**: `cd ~/.config/selene` and `selene ../nvim/lua`

This **succeeds** with the config mentioned in attempt 1 but fails with the configuration in attempt 2. Does that mean `selene.toml` should always be in the same working dir wherever selene command is run from? If yes, what purpose does `--config` serve?

**Attempt 4**: `selene.toml` and `vim.toml` are in `~/.config/nvim/lua/cfg`, the dir where `null-ls` is configured, `~/.config/nvim/lua/`, and `~/.config/nvim/` - one after the other

`null-ls` was configured not to use `--config` in this case and I see errors related to `vim` not being present using configs in both attempt 1 and 2

The only case where `null-ls` and `selene` don't complain about `vim` and **succeed** is when I execute `selene` or open neovim while being in the same dir wherever `selene.toml` is with the config mentioned in attempt 1.

I don't think it's feasible to create `selene.toml` and `vim.toml` in each and every folder on my operating system? How do I actually configure this linter to use the file in `~/.config/selene/selene.toml` with the contents in attempt 1?

**Comment by Kampfkarren** [comment]
To be clear, it's the STANDARD LIBRARY that it can't find, your selene.toml is fine. 

Using --config could search for std near that area, rather than in pwd.

**Comment by ayushnix** [comment]
> To be clear, it's the STANDARD LIBRARY that it can't find, your selene.toml is fine.

You mean the `vim.toml` file or does it expect a copy of the `lua51.toml` file?

> Using --config could search for std near that area, rather than in pwd

Sorry, maybe I'm missing something, but I still don't see how I can solve this issue. I can't have `vim.toml` all over the place right? Can I specify the contents of `vim.toml` in `selene.toml` such that it would work? This is what the attempt 2 config does I think but that attempt failed too.

**Comment by Kampfkarren** [comment]
vim.toml, there's actually a separate bug here where the ERROR says it's looking for lua51.toml, but that is built in. 

There's no way to solve the issue right now as a user, this is definitely something we should work on, I was just clarifying where the issue lies.

**Comment by natrys** [comment]
Stumbled upon this issue today. @ayushnix if you are still looking for a workaround, null-ls lets you further configure each source, in particular [the `cwd` callback](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#spawn-directory) defines the working directory for the spawned program.

This recursively searches upward from current buffer's directory looking for selene.toml, and failing that falls back to somewhere else:

```lua
local null_ls = require("null-ls")
null_ls.setup({
  sources = {
    null_ls.builtins.diagnostics.selene.with({
      cwd = function(_params)
        return vim.fs.dirname(
          vim.fs.find({'selene.toml'}, {upward = true, path = vim.api.nvim_buf_get_name(0)})[1]
        ) or vim.fn.expand("~/.config/selene/") -- fallback value
      end
    }),
  }
})
```

**Comment by ayushnix** [comment]
@natrys Thanks for the suggestion!
