### ISSUE TITLE
selene-vscode extension is not available for VSCodium

### ISSUE THREAD

**Issue by cassis163** [Kampfkarren/selene#343]
The selene-vscode extension is not available for [VSCodium](https://vscodium.com/), which is the editor that I personally use.

**Comment by Kampfkarren** [comment]
What would be needed to support this? It's already a bit of a pain to manage the VSC extension.

**Comment by bmos** [comment]
it does work though, you just have to download the file and add it manually.

**Comment by Kampfkarren** [comment]
From what I've quickly read online, it looks like you should be able to use the VS Code marketplace to install the selene extension, that or the vsix directly.

Other than that, it looks like the VSCodium marketplace I found (openvsx?) needs me to do a ton of work with Eclipse accounts or something, and I don't think I'm going to do that.
