### ISSUE TITLE
Cyclomatic complexity lint

### ISSUE THREAD

**Issue by jeparlefrancais** [Kampfkarren/selene#362]
It would be great if I could enable a lint to cap the cyclomatic complexity per function in a code base. This is pretty standard is most programming language.

(wikipedia [reference](https://en.wikipedia.org/wiki/Cyclomatic_complexity))

**Comment by Kampfkarren** [comment]
Would need to be off by default, but I'm okay with it.

**Comment by Kampfkarren** [comment]
Added with `high_cyclomatic_complexity`
