### ISSUE TITLE
Add `utf8` globals to `lua53.yaml`

### ISSUE THREAD

**Issue by ProspectPyxis** [Kampfkarren/selene#385]
Lua 5.3 has the [`utf8` global](https://q-syshelp.qsc.com/Content/Control_Scripting/Lua_5.3_Reference_Manual/Standard_Libraries/4_-_Basic_UTF-8_Support.htm) which provides basic support for utf-8 encoding. This seems to be missing from selene's standard library file for the version.

I'm willing to make a PR for this if needed.

**Comment by Kampfkarren** [comment]
Should be very approachable to work on! You can even potentially copy the definitions from roblox.yml
