### ISSUE TITLE
Non-zero exit code on only lint warnings

### ISSUE THREAD

**Issue by guidojw** [Kampfkarren/selene#404]
Currently, Selene exits the process with code 1 if there are only lint warnings. I expect Selene to, like other linters (ESLint), exit with an exit code of 0 here and only exit with non-zero exit codes on lint errors/parse errors.

![image](https://user-images.githubusercontent.com/35309288/187036435-ab7b03ce-fe4f-4257-ae77-62904303e9d8.png)

**Comment by Kampfkarren** [comment]
This is intentional, and changing this would require everyone who currently uses selene to update their CI to care about warnings. I don't like the gotcha of clippy having to add `-D warnings`, for instance.

What I would be okay with is an `--allow-warnings` or similar flag that's opt in.
