### ISSUE TITLE
Standard library loading doesn't support `yaml` extension

### ISSUE THREAD

**Issue by LastTalon** [Kampfkarren/selene#408]
When loading libraries configured in `selene.toml` such as `std = "roblox+testez"`, selene fails to load `testez.yaml` when its present. Works as intended after changing the file to `testez.yml`, but both of these are valid extensions for yaml files.

**Comment by sisco0** [comment]
Could you kindly ensure that the given patch in PR #441 solves the issue as expected @LastTalon @Kampfkarren?

Thank you in advance!
