### ISSUE TITLE
exclude option for selene.toml does not work

### ISSUE THREAD

**Issue by PysephWasntAvailable** [Kampfkarren/selene#437]
Using any of the `exclude = ["Client_Template.lua"]`, `exclude = ["**/Client_Template.lua"]` or `exclude = ["Path/To/Client_Template.lua"]` options in `selene.toml` does not exclude the files from being linted when running `selene ./src` in the VSCode terminal, as shown below:
![image](https://user-images.githubusercontent.com/45090858/193480518-59e40678-5734-4a8d-a1d9-07a829d6fe4d.png)
![image](https://user-images.githubusercontent.com/45090858/193480522-a4d916c4-e2e9-4419-b3e9-7b80e22512af.png)

**Comment by Kampfkarren** [comment]
Should be tested in the full runs

**Comment by Kampfkarren** [comment]
Nevermind! Apparently this isn't in 0.21.1 and the changelog (fixed in #438) confused me.
