### ISSUE TITLE
Don't require error message for `assert`

### ISSUE THREAD

**Issue by Qualadore** [Kampfkarren/selene#448]
I use `assert` frequently in my code to assert obvious invariants `#array > 0`, and to assert that something isn't `nil` `assert(value)`, sometimes for typechecking. Writing error messages for these is too verbose, so I simply pass an empty string to get Selene to accept it.

**Comment by Kampfkarren** [comment]
After wasting huge amounts of time trying to debug useless asserts, the correct behavior for selene is definitely to lint these.

That being said, feel free to *move* the existing assert *error* off to a new *warn*.
