### ISSUE TITLE
Selene incorrectly lints for unused variable for Luau types

### ISSUE THREAD

**Issue by bubshayz** [Kampfkarren/selene#450]
Consider the following Luau code:

```lua
local a =  {} -- unused variable, marked by selene
type b = typeof(a)
local t : b = {}
print(t)
```

Selene will incorrectly mark `a` as unused, since it fails to see that it is used in a type!

**Comment by Kampfkarren** [comment]
Duplicate of https://github.com/Kampfkarren/selene/issues/337
