### ISSUE TITLE
Selene not recognizing `table.clone`

### ISSUE THREAD

**Issue by NobleDraconian** [Kampfkarren/selene#454]
Currently, as of `v0.22.0` (0c631d55d720d53b4223d280a235bbdcb7861050), selene does not recognize the `table.clone` API. `selene generate-roblox-std` also does not include this information in the resulting std file.

![image](https://user-images.githubusercontent.com/26460940/199824213-8a01fd76-f6fa-442c-81cb-a50811cab932.png)

**Comment by Kampfkarren** [comment]
It should 😕 

https://github.com/Kampfkarren/selene/blob/main/selene-lib/default_std/luau.yml#L214-L217

**Comment by NobleDraconian** [comment]
@Kampfkarren Something seems to be broken then, I'm running the latest version of selene

**Comment by NobleDraconian** [comment]
...it turns out, I had an old selene std file laying around that selene was reading from, instead of the new one. 🤦‍♂️ 

This issue isn't a bug, it's user error.
