### ISSUE TITLE
`incorrect_standard_library_use` ignores overrides in standard libraries

### ISSUE THREAD

**Issue by tomodachi94** [Kampfkarren/selene#467]
The standard library I'm working with has a custom global/API named `fs`. I defined it in my standard lib (under `globals`), and I get this error when I run the linter.

Is this intended behavior or is this a bug?

**Comment by tomodachi94** [comment]
A workaround is disabling the `incorrect_standard_library_use` linter in `selene.toml`.

**Comment by Kampfkarren** [comment]
Can you show your standard library format, your code, and your selene.toml?

**Comment by Kampfkarren** [comment]
I'll play with this, thanks

**Comment by tomodachi94** [comment]
Also, quick question @Kampfkarren, does Selene have LSP functionality? If so, is it documented somewhere? I'd love to be able to get warnings about my code inside Neovim.

**Comment by Kampfkarren** [comment]
There's no LSP but there definitely are Neovim configs out there, a ton of Neovim people use selene

**Comment by Kampfkarren** [comment]
Oh, this isn't a bug, your standard library is just wrong

`property: read-only` means that it doesn't have any properties of its own: https://kampfkarren.github.io/selene/usage/std.html#properties

If you add something like:

```yml
fs.open:
    args:
    - type: string
```

...then it should work.
