### ISSUE TITLE
False positive `error[incorrect_standard_library_use]` for `table.unpack or unpack`

### ISSUE THREAD

**Issue by staticssleever668** [Kampfkarren/selene#480]
In my code I opportunistically use whatever implementation of table.unpack is available, however, this triggers a lint.

```lua
local unpack = table.unpack or unpack or error("There is no `table.unpack` implementation")
```

This means that selene doesn't check if you verify if the value is non-nil.

More verbose variation of the snippet also triggers the lint:

```lua
local unpack
if table.unpack then
	unpack = table.unpack
elseif unpack then
	unpack = unpack
else
	error("There is no `table.unpack` implementation")
end
```

(and also highlights that this problem is probably pretty hard to solve).

Also a note: sumneko/lua-language-server has this issue as well.

**Comment by Kampfkarren** [comment]
I would be super curious to see how much of this in the wild.

**Comment by Kampfkarren** [comment]
I don't really know how viable a fix on this would be. I would definitely want missing properties to error here, for instance.

I think this is just kind of the type of thing you need to use allow lints for, unless someone can come up with a great answer to this that's also resilient to typos.

**Comment by Kampfkarren** [comment]
Basically imagine something like `io.is_windowes and "I'm on Windows!"`, not noticing the typo

**Comment by Kampfkarren** [comment]
Ideally I think plugins would also let you conditionally retract lints, but I haven't written that out yet
