### ISSUE TITLE
[Rojo-Warn] Cannot add an instance from a patch that has no parent

### ISSUE THREAD

**Issue by Limeception** [Kampfkarren/selene#483]
<img width="678" alt="Screenshot 2023-01-24 at 10 03 00 AM" src="https://user-images.githubusercontent.com/114687251/214358997-fc9289e0-d1e5-491a-885c-0b2cbd2feeb2.png">
Not sure what this is, but it tells me to file an issue, so here it is. Sorry if it's irrelevant 😅.

**Comment by Kampfkarren** [comment]
You're on the wrong repository.
