### ISSUE TITLE
Certain Roblox globals falsely flagged as non-overridable

### ISSUE THREAD

**Issue by PeccNeck** [Kampfkarren/selene#485]
Attempting to override certain globals will cause Selene to throw an error.
> error[incorrect_standard_library_use]: standard library global `script` is not overridable
error[incorrect_standard_library_use]: standard library global `print` is not overridable
error[incorrect_standard_library_use]: standard library global `warn` is not overridable

I understand that, as a general rule, overwriting globals is bad practice, to put it lightly. It can be done though, and there *are* niche utilities for this; in my case, I'm overriding `script` so I can call `print`/`warn` in one script with custom logic, from another with the correct origin script attached.

It's quite irritating having Selene spit out errors from me doing this, even if I shouldn't be doing this; I'd still expect it to warn me of the "issue", but a full error is overblowing it, and I'd rather not have to disable `incorrect_standard_library_use` just to stop this.

**Comment by Kampfkarren** [comment]
Everything marked "not overridable" is technically overridable, but you should never be doing it. If you have a valid use case, put `-- selene: allow(incorrect_standard_library_use)` above the line, or append an extra standard library to patch these.
