### ISSUE TITLE
[question] std generation and std separation

### ISSUE THREAD

**Issue by Commandcracker** [Kampfkarren/selene#523]
## std generation

Is there some tool to generate a std ?

## std separation

Is it possible to have different std's per folder
Example:
/spec -> std: busted.yml
/ -> std: cc-tweaked.selene.yaml
/src -> std: cc-tweaked.selene.yaml

**Comment by Kampfkarren** [comment]
Standard library format is in the documentation, and there are a few examples in the codebase. No tool though. 

I'm not sure about your last question. selene.toml looks for libraries in where it is ran.

**Comment by Commandcracker** [comment]
@Kampfkarren

## Explanation

I meant if it is possible to run selene on the main folder and have a different selene.toml's in some folders.

## Example

```lua
📦project
 ┣ 📂spec
 ┃ ┣ 📜test_spec.lua -- should use /spec/selene.toml
 ┃ ┣ 📄busted.selene.yaml
 ┃ ┗ ⚙️selene.toml
 ┣ 📂src
 ┃ ┣ 📄cc-tweaked.selene.yaml
 ┃ ┣ 📜test.lua -- should use /src/selene.toml
 ┃ ┗ ⚙️selene.toml
 ┣ 📂some_folder
 ┃ ┗ 📜test.lua -- should use /selene.toml
 ┣ 📜test.lua -- should use /selene.toml
 ┗ ⚙️selene.toml
```
