### ISSUE TITLE
Need to use capitalized function name?

### ISSUE THREAD

**Issue by ShalokShalom** [Kampfkarren/selene#555]
Is this a bug, or just weird?

![Screenshot_20230924_163642](https://github.com/Kampfkarren/selene/assets/6344099/0052854a-44da-4a12-8061-bdc03ac6a71f)

That's the first time that I have ever seen, that the name of a function is needed to be named with a capitalized first letter.

**Comment by Kampfkarren** [comment]
That doesn't look like a selene error, I definitely wouldn't think of something like that :P
