### ISSUE TITLE
Errors in vscode extension related to "command 'selene.reinstall not found' error

### ISSUE THREAD

**Issue by Jaguar-515** [Kampfkarren/selene#57]
Currently, this bit of code in [extension.ts](https://github.com/Kampfkarren/selene/blob/master/selene-vscode/src/extension.ts) returns two "Expression expected" errors and one ": expected" error

```ts
const output = await selene.seleneCommand(
            context.globalStoragePath,
            "--display-style=json -",
            selene.Expectation.Stderr,
            vscode.workspace.getWorkspaceFolder(
                vscode.Uri.file(document.uri.fsPath),
            )?.uri?.fsPath,
            document.getText()
        )
```

![image](https://user-images.githubusercontent.com/48777426/69473722-6926c900-0d6c-11ea-8a37-3389ed2fe4f7.png)

This also limits the use of the Selene reinstall command, returning an "command 'selene.reinstall' not found error.

**Comment by Kampfkarren** [comment]
Your TypeScript is not up to date--make sure it's 3.7.
