### ISSUE TITLE
CFrame.lookalong isnt a valid member

### ISSUE THREAD

**Issue by LokiGitHubb** [Kampfkarren/selene#576]
I ported a project with CFrame.lookAlong() to VSCode, and seline counted it as a non-existent member.
![image](https://github.com/Kampfkarren/selene/assets/140853603/704fe121-a4d9-48da-9bde-6d22a61e5871)

**Comment by Kampfkarren** [comment]
New API, needs to be added to the base roblox file.

**Comment by LokiGitHubb** [comment]
wait so is this gonna be fixed?

**Comment by Kampfkarren** [comment]
These are the best PRs to make as a beginner. 

Here is an example: https://github.com/Kampfkarren/selene/pull/567
