### ISSUE TITLE
tick() triggers selene::undefined_variable

### ISSUE THREAD

**Issue by LucySweetWork** [Kampfkarren/selene#63]
When using tick() in code selene triggers the undefined_variable lint, even though when using Lua in Roblox tick is defined without initialization by the script.

**Comment by Kampfkarren** [comment]
This does not happen to me. Does it lint any other known Roblox globals?

**Comment by LucySweetWork** [comment]
Just had a look and yes, it's linting all Roblox globals, for example "spawn"

**Comment by Kampfkarren** [comment]
Did you follow the guide to using Selene for Roblox?

https://kampfkarren.github.io/selene/roblox.html

**Comment by LucySweetWork** [comment]
My mistake, assumed it worked with Roblox out the box, thanks!
