### ISSUE TITLE
Add option to reload standard library to VS code extension

### ISSUE THREAD

**Issue by evaera** [Kampfkarren/selene#65]
So reload window is not required

**Comment by Kampfkarren** [comment]
I don't remember why this was needed, considering the standard library *should* be being remade every time you type (since selene will run again).

It's been a while, do you remember why you needed this?

**Comment by evaera** [comment]
No, maybe changes to the standard library weren't being picked up in the linter?

**Comment by Kampfkarren** [comment]
That would make sense to me, but even then I think just typing will fix it.

I'll close this for now unless we remember and it's still relevant.
