### ISSUE TITLE
VSCode extension should create a 2nd notification when updating is finished

### ISSUE THREAD

**Issue by NobleDraconian** [Kampfkarren/selene#71]
Currently, selene creates a notification when an update for it is available. If you click the button to install the update, it never notifies you when it is done installing the update.
This can cause confusion, as a developer may potentially sit there for ~30 seconds waiting for it to give an indication that it finished updating when in reality the extension updated quicker than that.

Selene should create a notification when the update install is completed, so the developer doesn't have to guess when it's done installing.

**Comment by 05st** [comment]
![comment](https://user-images.githubusercontent.com/60903484/77855346-74c04b80-71b5-11ea-8766-2a6df611020d.png)
Is this fixed?

**Comment by Kampfkarren** [comment]
Should be.
