### ISSUE TITLE
VSCode extension stops linting if it encounters a symbol not used in Lua outside of a string literal

### ISSUE THREAD

**Issue by Dekkonot** [Kampfkarren/selene#76]
Adding a symbol that isn't used in Lua (`?`, `$`, `♧`, etc.) to a file outside of a string causes the VSCode extension to stop linting. Try this code snippet:

```lua
local thisShouldLint?
```

**Comment by Kampfkarren** [comment]
This would be because it's causing a full-moon error, but the extension doesn't process those yet. Whoops!

**Comment by Kampfkarren** [comment]
![image](https://user-images.githubusercontent.com/3190756/122656092-78b6f100-d10c-11eb-9266-d22d363bf343.png)


Looks like this was already fixed.
