### ISSUE TITLE
`table.unpack` is not detected by selene

### ISSUE THREAD

**Issue by Reshiram110** [Kampfkarren/selene#80]
In Roblox projects with a generated `roblox.toml` file, `table.unpack` is either not generated in the file or selene is not detecting it properly. Currently selene spits an error when it sees `table.unpack` being used.

![image](https://user-images.githubusercontent.com/26460940/72319387-0c110a80-366d-11ea-8650-3f1b03349890.png)

**Comment by dekkonot** [comment]
`table.unpack` is already in the standard library. Have you tried deleting your `roblox.toml` and regenerating it? It may be outdated.
