### ISSUE TITLE
Selene fails to parse inline comment with tabs

### ISSUE THREAD

**Issue by vocksel** [Kampfkarren/selene#86]
If a tab is used anywhere inside of an inline comment, Selene incorrectly thinks the following token is unexpected.

![image](https://user-images.githubusercontent.com/3081936/73147148-1deaa880-4084-11ea-9eda-ca087c27c735.png)

The exact comment is:
```lua
-- Hello	world
```

This blocks me from incorporating Selene into a project I'm currently being onboarded onto, as the existing comments use tabs for indentation.

**Comment by Kampfkarren** [comment]
Bug in full-moon: https://github.com/Kampfkarren/full-moon/issues/55. I'll look into this later tomorrow.

**Comment by Kampfkarren** [comment]
Fixed in 0.5.3.
