### ISSUE TITLE
Selene doesn't know what a decimal is

### ISSUE THREAD

**Issue by vocksel** [Kampfkarren/selene#87]
Without a leading 0, Selene encounters a parse error for decimal values.

```
local x = .5 -- fails
local x = 0.5 -- works
```

**Comment by Kampfkarren** [comment]
Bug in full-moon: https://github.com/Kampfkarren/full-moon/issues/58

**Comment by vocksel** [comment]
For parse errors, is it generally a good idea to first see if it's already something tracked in full moon?

**Comment by Kampfkarren** [comment]
Yeah, selene just uses full-moon internally.

**Comment by Kampfkarren** [comment]
This has been fixed since a full-moon upgrade.
