### ISSUE TITLE
luacheckrc migration

### ISSUE THREAD

**Issue by Stanzilla** [Kampfkarren/selene#89]
Hey there, are there any plans to add a migration for luacheckrc files into Selene's format or maybe a compat mode that uses luacheckrc instead?

**Comment by Kampfkarren** [comment]
A complete luacheckrc converter is likely out of scope--the file supports raw Lua rather than being strictly data. Aside from that, it shouldn't be too hard for you to manually convert them, especially since selene tells you the exact rules its linting against.
