### ISSUE TITLE
Selene panics when last character in file is part of a failed lint

### ISSUE THREAD

**Issue by dekkonot** [Kampfkarren/selene#93]
When the last character of a file is part of a failed lint, the program panics. As an example, if you run selene over a file with the contents ``foo = "bar"``, Selene throws: ``thread '<unnamed>' panicked at 'byte index 12 is out of bounds of `foo = "bar"`', src\libcore\str\mod.rs:2052:9``.

However, if even a space is added to the end of the file (making the source be ``foo = "bar" ``), the program runs just fine.

I'm not sure if this is a Selene or Full Moon error, but I am erring on the side of caution and opening this issue here.

**Comment by Kampfkarren** [comment]
![image](https://user-images.githubusercontent.com/3190756/75205107-c180b480-5727-11ea-8cf3-78246b3945f0.png)
This doesn't seem to happen to me.
