### ISSUE TITLE
Put executables into zip files in releases

### ISSUE THREAD

**Issue by LPGhatguy** [Kampfkarren/selene#95]
Currently, releases have bare executables attached to them, named `selene.exe`, `selene-mac`, and `selene-linux`. I think it would be an improvement to package these instead as zip files because:

- The executable name can be normalized to just `selene` on all platforms without needing to rename it.
- Zip files can preserve the permissions mask on Unix, alleviating the need to run `chmod +x`
- Rust executables are very compressible. With Rojo I saw my downloads get ~3x smaller.
- The name of the release artifact can be more specific, like including the version number and architecture. I found that this was useful once my download folder had many versions of the same tool.
- Artifacts from GitHub Actions come compressed in zip files anyways
-  Selene will become installable by [Foreman](https://github.com/rojo-rbx/foreman). 😄

**Comment by Kampfkarren** [comment]
Falls under the scope of the VS Code extension's auto downloading. Probably keep backwards compatible with the extension for a while.

**Comment by Kampfkarren** [comment]
Starting this with 0.6.0, but not closing this until we get the VS Code extension to work with zips so we can ditch bare executables entirely.
